### ISSUE TITLE
Event rankings missing best speeds

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#10]
Best results are sometimes missing from event rankings. Ttypically, slower results are listed instead.

Examples can be found in the [British Foil Speed Challenge 2022](https://www.gps-foilsurfing.com/default.aspx?mnu=eventranking&val=707) where some of the rankings for Michael George are incorrect; 2 sec, 500 m, 1852 m. 
 
It's not obvious whether the best speeds were ever listed or disappeared after posting a newer session.
 
This problem affects more than one user, despite the above examples only relating to Michael George.

**Comment by djong1** [comment]
Thanks for reporting, we will investigate this issue

**Comment by djong1** [comment]
we have identified the bug and will work on it to fix. The bug kicks in when users change the event for an existing session multiple time. The fix will not update the existing rankings, if you can provide a list with mismatching rankings that would be great (we can recreate the rankings per user in our admin module) otherwise, we can regenerate the ranking but doing this will take longer to fix because it needs a script to be created and executed.

**Comment by Logiqx** [comment]
I think it also affects sessions where I haven't (knowingly) changed the event.

e.g. https://www.gps-foilsurfing.com/default.aspx?mnu=user&val=388548&uid=2640 has a 500m of 27.31 which is not in the British Foil Speed Challenge 2022 rankings.

If you can rebuild UID 2640 on gps-foilsurfing (which is my user), I'll let you know which other ones are incorrect when I rediscover them.

Thanks!

**Comment by jhdebruin** [comment]
Hi, just did a rebuild for UID 2640 on event ID - 707 (BFSC 2022) , could you please confirm if its ok now ? @Logiqx thnx

**Comment by Logiqx** [comment]
That's fine now. Thanks.

**Comment by jhdebruin** [comment]
Fix (structural and fixes)

**Comment by Logiqx** [comment]
One final note on this issue (which is now closed) about the Python script I wrote to find all instances of this issue on GP3S.

A report showing all instances of this issue on GP3S is now available - https://logiqx.github.io/gp3s-query/events/
