### ISSUE TITLE
Friends ranking gives error 500 ( since 12-12-2022)

### ISSUE THREAD

**Issue by jhdebruin** [djong1/gp3s#120]
Friends ranking gives error 500 ( since 12-12-2022)![image](https://user-images.githubusercontent.com/109060128/209143230-147e531c-23c8-4605-8687-36768e414820.jpeg)

![image](https://user-images.githubusercontent.com/109060128/209143251-bc623882-3757-4d1f-a98b-64fe32b44f55.jpeg)

**Comment by bjorn76** [comment]
Ranking works it is the stat that fails

**Comment by bjorn76** [comment]
![Screenshot_20221222-153823_Chrome](https://user-images.githubusercontent.com/15274391/209158095-a16f0fc1-ba4d-4fa3-a6ac-900fad75412f.jpg)

**Comment by bjorn76** [comment]
Actally all * Stat links fails

**Comment by bjorn76** [comment]
No, I have the error on Win 10 Chrome, Edge and Fire fox too. The screen shoots were from Chrome on an Android mobile (just because I was traveling yesterday) and that combo also have the issue

I've posted on a Swedish fb group to confirm that others having issues too. Others having issues too but one user posted it works on Firefox.  That makes me suspect issues with Microsoft login. That has caused me issues to login in the past.

**Comment by djong1** [comment]
Hi Björn, can you test validate a few steps for me?

- Can you actively logout and login again and test Stats. 
- Can you clear your browser cache   And test stats again 

Thanks in advance

**Comment by bjorn76** [comment]
Done so with FireFox now. I still have issues

**Comment by bjorn76** [comment]
I am not sure that it is related but ****Azure B2C login to the API portal fails too**. It was working fine a year ago or so.

**Comment by djong1** [comment]
Thanks for reporting, fixed the graph module. This was causing the issue.

**Comment by bjorn76** [comment]
Thanks! Solved fast and a wellcomed Christmas gift. Now we can assess 2022 and set new goals for 2023.🤙 (Confirmed working on Chrome on my Android )
