### ISSUE TITLE
Events are automatically linked to sessions

### ISSUE THREAD

**Issue by SurferTH** [djong1/gp3s#153]
And that’s a problem, because we run a challenge that is specific for one location. So If you surf elsewhere it should not be listed in this event.

**Comment by jhdebruin** [comment]
Will ad some useful background info to the comment of @SurferTH ; as described above its not possible to understand the issue:

1. A local event is running ( https://www.gps-speedsurfing.com/default.aspx?mnu=event&val=787 ), event appears to be based on country and not on specific spot ?? 
2. Session of https://www.gps-speedsurfing.com/default.aspx?mnu=user&val=400753&uid=23642&spotid=19396 is added to this event, and it should not because its sailed at Tenerife (not included in scope of the event)

**Comment by jhdebruin** [comment]
In general, please describe issues as complete as possible, including links to sessions, screenshots etc etc etc . We have only limited time available for fixing and deterring the right prio. The more info available , less time it takes for us to get the picture as sharp as possible....

**Comment by djong1** [comment]
the event is created with the wrong scope, it is created with scope world while it should be spot. Please provide the correct spotid or name than we can fix this for you. @SurferTH

**Comment by jhdebruin** [comment]
@djong1 

Spotname = [Zuidlaardermeer]
SpotID = 302

**Comment by SurferTH** [comment]
The creator of the event is not able to change the spotname… What is he doing wrong?

**Comment by jhdebruin** [comment]
Will be fixed by us

**Comment by djong1** [comment]
creator is not allowed to change spot name because this has some serious ranking affects. Spot name change is a manual change that need to be requested via email.

**Comment by djong1** [comment]
spot is zuidlaardermeer and scope is spot, should be fine now
