### ISSUE TITLE
Garmin synchr. and *.gpx files uplod problems

### ISSUE THREAD

**Issue by Siejonek** [djong1/gp3s#182]
I have connected Garmin Fenix 6XPRO to my account, but it does not work. The session is calculated without success. Also when I try to upload sessions via *.gpx file website shows avr speed=0 or false speed.
I checked my *.gpx files in GPSResultsV6 and there is everything OK.
Do you have any remedy?

**Comment by jhdebruin** [comment]
Could you drop the file here or mail it to info@gps-speedsurfing.com ?

**Comment by jhdebruin** [comment]
Hi @Siejonek , i don't see any attachments, could you mail them please to info@gps-speedsurfing.com

**Comment by jhdebruin** [comment]
Tracks are rejected because is doesn’t contain a solid 1 per second logging, see basic rules (->  https://www.gps-speedsurfing.com/default.aspx?mnu=item&item=gpsother ) . For example to use a Garmin device, make sure it’s configured to log at once per second -> 
https://www.cnet.com/how-to/the-one-setting-you-should-change-on-your-garmin-watch/

Afterwards please use the .gpx extension to post your session.

**Comment by Siejonek** [comment]
Thanks for yours prompt reply
