### ISSUE TITLE
Pre posting screen

### ISSUE THREAD

**Issue by Paularn35** [djong1/gp3s#227]
When trying to post new windsurf session I don’t see my results screen prior to pushing add button,I can’t see my 5 best 10 secs my alpha 250 ,500,mile nothing at all .
Can you confirm if there is a fault ,I thought it was because my subscription had run out but have now renewed still the same,thanks

**Comment by djong1** [comment]
Can you attach a screenshot and please sent us your track to check it. Thanks

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Paularn35 ***@***.***>
Verzonden: Saturday, October 14, 2023 3:13:37 PM
Aan: djong1/gp3s ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [djong1/gp3s] Pre posting screen (Issue #227)


When trying to post new windsurf session I don’t see my results screen prior to pushing add button,I can’t see my 5 best 10 secs my alpha 250 ,500,mile nothing at all .
Can you confirm if there is a fault ,I thought it was because my subscription had run out but have now renewed still the same,thanks

**Comment by jhdebruin** [comment]
This page has been adjusted, all "non"  adjustable fields are no longer displayed,  we are planning a new session post interface in the next months, based on user feedback we will make some design for it
