### ISSUE TITLE
no speeds , when posting 

### ISSUE THREAD

**Issue by Erwinrovers** [djong1/gp3s#228]
goodday
when ik post  my session , i dont see speeds or any  other info on the screen 
<img width="1103" alt="Schermafbeelding 2023-10-15 om 13 30 30" src="https://github.com/djong1/gp3s/assets/122383988/1cc26004-f5f2-4595-9c60-2495f7bcf5d9">

greetings

erwin

**Comment by djong1** [comment]
yes, that is correct We have removed the data from the screen because it was giving too much info and people got distracted and confused. Just click add and you will see the results
________________________________
Van: Erwinrovers ***@***.***>
Verzonden: zondag 15 oktober 2023 13:33
Aan: djong1/gp3s ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [djong1/gp3s] no speeds , when posting (Issue #228)


goodday
when ik post my session , i dont see speeds or any other info on the screen
[Schermafbeelding 2023-10-15 om 13 30 30]<https://user-images.githubusercontent.com/122383988/275322840-1cc26004-f5f2-4595-9c60-2495f7bcf5d9.png>

greetings

erwin

**Comment by Erwinrovers** [comment]
Ok thanks gor the Info

Grt

Erwin

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Dylan de Jong ***@***.***>
Verzonden: Sunday, October 15, 2023 4:32:21 PM
Aan: djong1/gp3s ***@***.***>
CC: Erwinrovers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [djong1/gp3s] no speeds , when posting (Issue #228)


yes, that is correct We have removed the data from the screen because it was giving too much info and people got distracted and confused. Just click add and you will see the results
________________________________
Van: Erwinrovers ***@***.***>
Verzonden: zondag 15 oktober 2023 13:33
Aan: djong1/gp3s ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [djong1/gp3s] no speeds , when posting (Issue #228)


goodday
when ik post my session , i dont see speeds or any other info on the screen
[Schermafbeelding 2023-10-15 om 13 30 30]<https://user-images.githubusercontent.com/122383988/275322840-1cc26004-f5f2-4595-9c60-2495f7bcf5d9.png>

greetings

erwin

**Comment by jhdebruin** [comment]
This page has been adjusted, all "non"  adjustable fields are no longer displayed,  we are planning a new session post interface in the next months, based on user feedback we will make some design for it

**Comment by Erwinrovers** [comment]
Nice to hear , keep up the good work Guys 👌🏻💪🏻

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Jan Hendrik de Bruin ***@***.***>
Verzonden: Monday, October 16, 2023 10:04:57 AM
Aan: djong1/gp3s ***@***.***>
CC: Erwinrovers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [djong1/gp3s] no speeds , when posting (Issue #228)


This page has been adjusted, all "non" adjustable fields are no longer displayed, we are planning a new session post interface in the next months, based on user feedback we will make some design for it
