### ISSUE TITLE
Changing groupe age loose all results in that group age category

### ISSUE THREAD

**Issue by BBLSurfer** [djong1/gp3s#234]
I have noticed that when you are changing group age 
Junior+  to senior for example (applies for all going up category Junior-> junior+, senior to Master, Master to GM, GM to SM etc..)
Then all your scores/PRs done while in the Junior+ group are disappearing from the result of this age category (or any year you have done it)

I believe they should stay on records so that any other member in that age group can beat you.  (applies to any age category).

For example : 
Floris W. or Franek D. recently moved to senior and all their good speeds while they were 15-18y are gone
https://www.gps-speedsurfing.com/default.aspx?mnu=rankings&Year=-&Tab=0&Gender=0&WeightClass=0&AgeClass=9&SpeedType=2

Also it appears that their old results (dunkerbeck speed challenge 2022 2021 etc... ) also do not mention their name anymore (in the junior+) because the calculation method is wrong and does not include the age at the time of the event (only the age at the time of display).

So looks like there are 2 ways : 
* calculate at the date of the event and freeze the results. 
Or 
* calculate so that the age of the rider at the date of the event of the year of the event is correct.
Example :  Results 2021 should be age of the rider now (20y) - time difference (2023-2021=2) so 18y.

Hope I explained it correctly.
I think it will be better overall for all the riders scoring high in their age category so that their best score stays in this category for anyone else to come and beat them.

**Comment by djong1** [comment]
Thanks for the detailed explanation, much appreciated. 

Currently, this is by design. So, when a user change age class and he or she improves his PR, all time is set to the corresponding sessions and the age class at that time. So indeed when a user changes an age class and he improves his PR, the historical record session will disappear from the all time ranking in his old age class. 
However the historical session will still be visible for corresponding year, so for instance for Floris his previous PR on the 250 when he was still in the 15-18 age class, is still visible when you select 2020. 
So the all-time ranking shows the actual PB times to beat with active competitors and the year ranking shows the real ranking of the given year despite if it is a PB or not.  

I hopes this creates more clarity's. But I agree we could do a better job in explaining here. If you have suggestions how to make this more clear let us know.

**Comment by BBLSurfer** [comment]
Hi Dylan,

Thanks for the explanation.
I kind of disagree with the fact that this is made on purpose, because you can see it does not apply to all the riders the same way.

Here the all time 15/18y 250m
https://www.gps-speedsurfing.com/default.aspx?mnu=rankings&Year=-&Tab=0&Gender=0&WeightClass=0&AgeClass=9&SpeedType=2
Why are Cyril, Liam, or Thomas or even Ennio or Jakob even there. If we apply what you wrote under they should be out of this all-time ranking as well (like Floris is)
As they are all in the above category 19-35… except those guys have stopped posting on your site before they changed group age or another issue why the results are not updated.

Same applies to other categories
let s check the 35-50
https://www.gps-speedsurfing.com/default.aspx?mnu=rankings&Year=-&Tab=0&Gender=0&WeightClass=0&AgeClass=4&SpeedType=2
Laurent Fesquet is in that group (he is 57 now), Jacques is 51 so is Harald, so based on your explanation they should also not be in that ranking but in the master 50-59 ranking.
While based on what I am suggesting, the ranking is based on the age then it is correct and all 3 riders Laurent, Jacques, and Harald are correct in that specific group age ranking as their score is the best they did while they were in that 35-50y old ranking.

What I m suggesting is that the general ranking or year ranking in the past is based on the age of the rider at the time of the run.
I can feel how difficult this is to implement, as the database must not be storing the age of the rider at the time of the run, but maybe something like this could be added.
 
Add a column age group in the line where the day run is stored, run a big calculation (group age = date of birth - day of run) on the existing raws in the database 
To calculate that field and fill it up for all past lines. Then run the yearly or age category based on that field. Of course, all new inserted runs should have the category inserted as well (but that is easier to implement).

Yes to have discussed this with my dad IT guy also, this is hell to fix, but this should be the right thing to do to have the proper records.
Agreed also not the bug you want to spend months coding on it, because of the low visibility effect, so just a suggestion really.

Anyway, not sure what you guys are coding in as language, but Dad said he will be happy to help you out implementing it if you re happy to share it, or have a test DB where this can be tested, added 
If you feel this should be done, if not then no worries, thanks for checking it out.

Brendan

**Comment by djong1** [comment]
Hi Brendan,

Cyril, Liam, or Thomas, Ennio or Jakob are still there because they did not improve their PB. So the PB is still achieved in the younger age class. If for instance Liam will go to Luderitz next year and set a new PB on 250 his old PB will vanish from the Youth age group since he has a new PB in the Senior age group.

So the leading principal is PB not Age class. Since you can only have one PB in a given time range (month, year, history) and age class is just an attribute of a PB, the same for gear. We did not setup the rankings based on a PB per age_class.

But, I'm always open to see how we can add things. To give a bit more insight for your dad, we already store the age_class attribute for every session. We applied the same for PB data sets. The only limiting fact is that you can only have one PB per time dimension (month, year, history). If we add age as a second dimension it will be an impactful change to the data model. If we need to do this I rather change the whole concept to a dynamic model (calculate on run time in multiple dimensions). Problem is that this will be a bit costly to run and given the fact we have very limited fundings from the community it is a challenge. But always open to learn and discover.

**Comment by BBLSurfer** [comment]
Ok got it 
Thank you Dylan, have a nice day.
Brendan
