### ISSUE TITLE
API - request to support also foilsurfing and optional other

### ISSUE THREAD

**Issue by djong1** [djong1/gp3s#24]
Requested in issue #15 to support all gps sites in the api

**Comment by djong1** [comment]
@Logiqx please check the API for foilsurfing event results

**Comment by Logiqx** [comment]
@djong1 The API appears to behave as it has done when I first tried it a few days ago.

Event_Rankings:
- Returns ranking data that seems to reflect gps-foilsurfing.com
  - It also contains addition rankings from a handful of gps-speedsurfing sessions. My Python script will report these oddities.
- Session URLs point to https://www.gps-speedsurfing.com
  - This isn't the end of the world because the ID parameters in the URL are still correct.

Event_Sessions:
- Only returns sessions which were originally posted to gps-speedsurfing, not foilsurfing. This is the main issue right now.
  - e.g. Event 707 (British Foil Challenge 2022) returns just 3 sessions which are gps-speedsurfing sessions
- Session URLs point to https://www.gps-speedsurfing.com
  - This isn't the end of the world because the ID parameters in the URL are still correct.

I also tried subscirbing to the professional API to see if that behaves differently but awaiting the "requested" to be approved.

n.b. I don't plan to use the brand / equipment APIs in the foreseeable future.

**Comment by djong1** [comment]
implemented in preview over the weekend. Please have a look at the Foil Api. @Logiqx

**Comment by djong1** [comment]
@Logiqx api available for other websites, url change need to be done, also data format change

**Comment by djong1** [comment]
url change implemented

**Comment by Logiqx** [comment]
@djong1 - new APIs seem fine

@jhdebruin - event reports generated for speed, foil, kite and ice

https://logiqx.github.io/gp3s-query/
