### ISSUE TITLE
Auto upload o f.oao file does not work anymore

### ISSUE THREAD

**Issue by timotte0909** [djong1/gp3s#39]
since yesterday I am not able to autoupload .oao files from my Motion devices. 

The upload seems to work, but then the speed calculation takes forever and never completes. 

two .oao files are not working. A friend has the same problem.

Please check.
![D7E057B7-2789-4FCE-913C-B3BF4D9CCD4C](https://user-images.githubusercontent.com/110685779/184239356-62ce86b4-495a-487d-8c16-7be691dc25c7.jpeg)

**Comment by djong1** [comment]
Thanks for reporting, we experience some issues after upgrade with our Kubernetes service. This containers could not be upgraded due to a new container registry location was added for the system node pool and we block outgoing request to unknown resource locations. Wea have added this new address, and everything should work again.
